// <auto-generated />
using System;
using ConsoleApp2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleApp2.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20251007063232_NewTables4")]
    partial class NewTables4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConsoleApp2.Models.AirMass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AirMass");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = 1,
                            Name = "1.0 EN 410"
                        });
                });

            modelBuilder.Entity("ConsoleApp2.Models.CalculationState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CalculationState");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = 1,
                            Name = "Calculated"
                        },
                        new
                        {
                            Id = 2,
                            Code = 2,
                            Name = "Has warnings"
                        },
                        new
                        {
                            Id = 3,
                            Code = 3,
                            Name = "Has errors"
                        });
                });

            modelBuilder.Entity("ConsoleApp2.Models.Illuminant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Illuminant");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = 1,
                            Name = "A"
                        },
                        new
                        {
                            Id = 2,
                            Code = 2,
                            Name = "C"
                        },
                        new
                        {
                            Id = 3,
                            Code = 3,
                            Name = "D65"
                        });
                });

            modelBuilder.Entity("ConsoleApp2.Models.Layer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<int>("LayerTypeId")
                        .HasColumnType("int");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<int>("MakeupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LayerTypeId");

                    b.HasIndex("MakeupId");

                    b.ToTable("Layer");
                });

            modelBuilder.Entity("ConsoleApp2.Models.LayerType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LayerType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = 1,
                            Name = "Substrate"
                        },
                        new
                        {
                            Id = 2,
                            Code = 2,
                            Name = "AirGap"
                        },
                        new
                        {
                            Id = 3,
                            Code = 3,
                            Name = "PVB"
                        });
                });

            modelBuilder.Entity("ConsoleApp2.Models.Makeup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CalculationStateId")
                        .HasColumnType("int");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MakeupTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("NominalWeight")
                        .HasColumnType("float");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("Slope")
                        .HasColumnType("int");

                    b.Property<string>("SoundReduction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CalculationStateId");

                    b.HasIndex("MakeupTypeId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Makeup");
                });

            modelBuilder.Entity("ConsoleApp2.Models.MakeupType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MakeupType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = 1,
                            Icon = "mono.png",
                            Name = "Mono",
                            ShortName = "Mono"
                        },
                        new
                        {
                            Id = 2,
                            Code = 2,
                            Icon = "double.png",
                            Name = "Double",
                            ShortName = "DBU"
                        },
                        new
                        {
                            Id = 3,
                            Code = 3,
                            Icon = "tripe.png",
                            Name = "Triple",
                            ShortName = "TBU"
                        });
                });

            modelBuilder.Entity("ConsoleApp2.Models.MakeupWarning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("MakeupId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WarningTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MakeupId");

                    b.HasIndex("WarningTypeId");

                    b.ToTable("MakeupWarning");
                });

            modelBuilder.Entity("ConsoleApp2.Models.Observer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Observer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = 1,
                            Name = "2 градуса"
                        },
                        new
                        {
                            Id = 2,
                            Code = 2,
                            Name = "10 градусов"
                        },
                        new
                        {
                            Id = 3,
                            Code = 3,
                            Name = "Сумеречный вид"
                        });
                });

            modelBuilder.Entity("ConsoleApp2.Models.Parameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Parameter");
                });

            modelBuilder.Entity("ConsoleApp2.Models.ParameterValue", b =>
                {
                    b.Property<int>("ParameterId")
                        .HasColumnType("int");

                    b.Property<int>("MakeupId")
                        .HasColumnType("int");

                    b.Property<double?>("Value")
                        .HasColumnType("float");

                    b.HasKey("ParameterId", "MakeupId");

                    b.HasIndex("MakeupId");

                    b.ToTable("ParameterValue");
                });

            modelBuilder.Entity("ConsoleApp2.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AirMassId")
                        .HasColumnType("int");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IlluminantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ObserverId")
                        .HasColumnType("int");

                    b.Property<int>("StandartId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AirMassId");

                    b.HasIndex("IlluminantId");

                    b.HasIndex("ObserverId");

                    b.HasIndex("StandartId");

                    b.ToTable("Project");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AirMassId = 1,
                            Code = 1,
                            CreationDate = new DateTime(2025, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IlluminantId = 1,
                            ModificationDate = new DateTime(2025, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Test project 01",
                            ObserverId = 1,
                            StandartId = 1
                        });
                });

            modelBuilder.Entity("ConsoleApp2.Models.Standart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Standart");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = 1,
                            Name = "ГОСТ"
                        },
                        new
                        {
                            Id = 2,
                            Code = 2,
                            Name = "EN"
                        },
                        new
                        {
                            Id = 3,
                            Code = 3,
                            Name = "NFRC"
                        });
                });

            modelBuilder.Entity("ConsoleApp2.Models.WarningType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WarningType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = 1,
                            Name = "Error"
                        },
                        new
                        {
                            Id = 2,
                            Code = 2,
                            Name = "Warning"
                        });
                });

            modelBuilder.Entity("ConsoleApp2.Models.Layer", b =>
                {
                    b.HasOne("ConsoleApp2.Models.LayerType", "LayerType")
                        .WithMany()
                        .HasForeignKey("LayerTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsoleApp2.Models.Makeup", null)
                        .WithMany("Layers")
                        .HasForeignKey("MakeupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LayerType");
                });

            modelBuilder.Entity("ConsoleApp2.Models.Makeup", b =>
                {
                    b.HasOne("ConsoleApp2.Models.CalculationState", "CalculationState")
                        .WithMany()
                        .HasForeignKey("CalculationStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsoleApp2.Models.MakeupType", "MakeupType")
                        .WithMany()
                        .HasForeignKey("MakeupTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsoleApp2.Models.Project", "Project")
                        .WithMany("Makeups")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalculationState");

                    b.Navigation("MakeupType");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ConsoleApp2.Models.MakeupWarning", b =>
                {
                    b.HasOne("ConsoleApp2.Models.Makeup", null)
                        .WithMany("Warnings")
                        .HasForeignKey("MakeupId");

                    b.HasOne("ConsoleApp2.Models.WarningType", "WarningType")
                        .WithMany()
                        .HasForeignKey("WarningTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WarningType");
                });

            modelBuilder.Entity("ConsoleApp2.Models.ParameterValue", b =>
                {
                    b.HasOne("ConsoleApp2.Models.Makeup", "Makeup")
                        .WithMany("ParameterValues")
                        .HasForeignKey("MakeupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsoleApp2.Models.Parameter", "Parameter")
                        .WithMany("ParameterValues")
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Makeup");

                    b.Navigation("Parameter");
                });

            modelBuilder.Entity("ConsoleApp2.Models.Project", b =>
                {
                    b.HasOne("ConsoleApp2.Models.AirMass", "AirMass")
                        .WithMany()
                        .HasForeignKey("AirMassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsoleApp2.Models.Illuminant", "Illuminant")
                        .WithMany()
                        .HasForeignKey("IlluminantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsoleApp2.Models.Observer", "Observer")
                        .WithMany()
                        .HasForeignKey("ObserverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsoleApp2.Models.Standart", "Standart")
                        .WithMany()
                        .HasForeignKey("StandartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AirMass");

                    b.Navigation("Illuminant");

                    b.Navigation("Observer");

                    b.Navigation("Standart");
                });

            modelBuilder.Entity("ConsoleApp2.Models.Makeup", b =>
                {
                    b.Navigation("Layers");

                    b.Navigation("ParameterValues");

                    b.Navigation("Warnings");
                });

            modelBuilder.Entity("ConsoleApp2.Models.Parameter", b =>
                {
                    b.Navigation("ParameterValues");
                });

            modelBuilder.Entity("ConsoleApp2.Models.Project", b =>
                {
                    b.Navigation("Makeups");
                });
#pragma warning restore 612, 618
        }
    }
}
