// <auto-generated />
using System;
using ConsoleApp2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleApp2.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20251003135130_ParameterValueTable01")]
    partial class ParameterValueTable01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConsoleApp2.Models.Makeup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Makeup");
                });

            modelBuilder.Entity("ConsoleApp2.Models.Parameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Parameter");
                });

            modelBuilder.Entity("ConsoleApp2.Models.ParameterValue", b =>
                {
                    b.Property<int>("MakeupId")
                        .HasColumnType("int");

                    b.Property<int>("ParameterId")
                        .HasColumnType("int");

                    b.Property<double?>("Value")
                        .HasColumnType("float");

                    b.HasKey("MakeupId", "ParameterId");

                    b.HasIndex("ParameterId");

                    b.ToTable("ParameterValue");
                });

            modelBuilder.Entity("ConsoleApp2.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StandartId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StandartId");

                    b.ToTable("Project");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = 1,
                            CreationDate = new DateTime(2025, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModificationDate = new DateTime(2025, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Test project 01",
                            StandartId = 1
                        });
                });

            modelBuilder.Entity("ConsoleApp2.Models.Standart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Standart");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = 1,
                            Name = "ГОСТ"
                        },
                        new
                        {
                            Id = 2,
                            Code = 2,
                            Name = "EN"
                        },
                        new
                        {
                            Id = 3,
                            Code = 3,
                            Name = "NFRC"
                        });
                });

            modelBuilder.Entity("ConsoleApp2.Models.Makeup", b =>
                {
                    b.HasOne("ConsoleApp2.Models.Project", null)
                        .WithMany("Makeups")
                        .HasForeignKey("ProjectId");
                });

            modelBuilder.Entity("ConsoleApp2.Models.ParameterValue", b =>
                {
                    b.HasOne("ConsoleApp2.Models.Makeup", "Makeup")
                        .WithMany("ParameterValues")
                        .HasForeignKey("MakeupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsoleApp2.Models.Parameter", "Parameter")
                        .WithMany("ParameterValues")
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Makeup");

                    b.Navigation("Parameter");
                });

            modelBuilder.Entity("ConsoleApp2.Models.Project", b =>
                {
                    b.HasOne("ConsoleApp2.Models.Standart", "Standart")
                        .WithMany("Projects")
                        .HasForeignKey("StandartId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Standart");
                });

            modelBuilder.Entity("ConsoleApp2.Models.Makeup", b =>
                {
                    b.Navigation("ParameterValues");
                });

            modelBuilder.Entity("ConsoleApp2.Models.Parameter", b =>
                {
                    b.Navigation("ParameterValues");
                });

            modelBuilder.Entity("ConsoleApp2.Models.Project", b =>
                {
                    b.Navigation("Makeups");
                });

            modelBuilder.Entity("ConsoleApp2.Models.Standart", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
