// <auto-generated />
using System;
using ConsoleApp2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleApp2.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("CoatingSequence");

            modelBuilder.Entity("ConsoleApp2.Models.AirMass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AirMass", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = 1,
                            Name = "1.0 EN 410"
                        });
                });

            modelBuilder.Entity("ConsoleApp2.Models.CalculationState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CalculationState", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = 1,
                            Name = "Calculated"
                        },
                        new
                        {
                            Id = 2,
                            Code = 2,
                            Name = "Has warnings"
                        },
                        new
                        {
                            Id = 3,
                            Code = 3,
                            Name = "Has errors"
                        });
                });

            modelBuilder.Entity("ConsoleApp2.Models.Coating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR [CoatingSequence]");

                    SqlServerPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<int?>("CoatingSurfaceId")
                        .HasColumnType("int");

                    b.Property<int?>("CoatingTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CoatingSurfaceId");

                    b.HasIndex("CoatingTypeId");

                    b.ToTable("Coating", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("ConsoleApp2.Models.CoatingSurface", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CoatingSurface", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = 1,
                            Name = "Inner"
                        },
                        new
                        {
                            Id = 2,
                            Code = 2,
                            Name = "Outer"
                        });
                });

            modelBuilder.Entity("ConsoleApp2.Models.CoatingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CoatingType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = 1,
                            Name = "Film"
                        },
                        new
                        {
                            Id = 2,
                            Code = 2,
                            Name = "Frit"
                        });
                });

            modelBuilder.Entity("ConsoleApp2.Models.GasType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GasType", (string)null);
                });

            modelBuilder.Entity("ConsoleApp2.Models.Illuminant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Illuminant", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = 1,
                            Name = "A"
                        },
                        new
                        {
                            Id = 2,
                            Code = 2,
                            Name = "C"
                        },
                        new
                        {
                            Id = 3,
                            Code = 3,
                            Name = "D65"
                        });
                });

            modelBuilder.Entity("ConsoleApp2.Models.Layer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<int>("LayerTypeId")
                        .HasColumnType("int");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<int>("MakeupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LayerTypeId");

                    b.HasIndex("MakeupId");

                    b.ToTable("Layer", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ConsoleApp2.Models.LayerType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LayerType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = 1,
                            Name = "Substrate"
                        },
                        new
                        {
                            Id = 2,
                            Code = 2,
                            Name = "AirGap"
                        },
                        new
                        {
                            Id = 3,
                            Code = 3,
                            Name = "PVB"
                        });
                });

            modelBuilder.Entity("ConsoleApp2.Models.Makeup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CalculationStateId")
                        .HasColumnType("int");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MakeupTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("NominalWeight")
                        .HasColumnType("float");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("Slope")
                        .HasColumnType("int");

                    b.Property<string>("SoundReduction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CalculationStateId");

                    b.HasIndex("MakeupTypeId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Makeup", (string)null);
                });

            modelBuilder.Entity("ConsoleApp2.Models.MakeupType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MakeupType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = 1,
                            Icon = "mono.png",
                            Name = "Mono",
                            ShortName = "Mono"
                        },
                        new
                        {
                            Id = 2,
                            Code = 2,
                            Icon = "double.png",
                            Name = "Double",
                            ShortName = "DBU"
                        },
                        new
                        {
                            Id = 3,
                            Code = 3,
                            Icon = "tripe.png",
                            Name = "Triple",
                            ShortName = "TBU"
                        });
                });

            modelBuilder.Entity("ConsoleApp2.Models.MakeupWarning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("MakeupId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WarningTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MakeupId");

                    b.HasIndex("WarningTypeId");

                    b.ToTable("MakeupWarning", (string)null);
                });

            modelBuilder.Entity("ConsoleApp2.Models.Observer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Observer", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = 1,
                            Name = "2 градуса"
                        },
                        new
                        {
                            Id = 2,
                            Code = 2,
                            Name = "10 градусов"
                        },
                        new
                        {
                            Id = 3,
                            Code = 3,
                            Name = "Сумеречный вид"
                        });
                });

            modelBuilder.Entity("ConsoleApp2.Models.PVBType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PVBType", (string)null);
                });

            modelBuilder.Entity("ConsoleApp2.Models.Parameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Parameter", (string)null);
                });

            modelBuilder.Entity("ConsoleApp2.Models.ParameterValue", b =>
                {
                    b.Property<int>("ParameterId")
                        .HasColumnType("int");

                    b.Property<int>("MakeupId")
                        .HasColumnType("int");

                    b.Property<double?>("Value")
                        .HasColumnType("float");

                    b.HasKey("ParameterId", "MakeupId");

                    b.HasIndex("MakeupId");

                    b.ToTable("ParameterValue", (string)null);
                });

            modelBuilder.Entity("ConsoleApp2.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AirMassId")
                        .HasColumnType("int");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IlluminantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ObserverId")
                        .HasColumnType("int");

                    b.Property<int>("StandartId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AirMassId");

                    b.HasIndex("IlluminantId");

                    b.HasIndex("ObserverId");

                    b.HasIndex("StandartId");

                    b.ToTable("Project", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AirMassId = 1,
                            Code = 1,
                            CreationDate = new DateTime(2025, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IlluminantId = 1,
                            ModificationDate = new DateTime(2025, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Test project 01",
                            ObserverId = 1,
                            StandartId = 1,
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("ConsoleApp2.Models.Standart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Standart", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = 1,
                            Name = "ГОСТ"
                        },
                        new
                        {
                            Id = 2,
                            Code = 2,
                            Name = "EN"
                        },
                        new
                        {
                            Id = 3,
                            Code = 3,
                            Name = "NFRC"
                        });
                });

            modelBuilder.Entity("ConsoleApp2.Models.SubstrateType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SubstrateType", (string)null);
                });

            modelBuilder.Entity("ConsoleApp2.Models.WarningType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WarningType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = 1,
                            Name = "Error"
                        },
                        new
                        {
                            Id = 2,
                            Code = 2,
                            Name = "Warning"
                        });
                });

            modelBuilder.Entity("ConsoleApp2.Models.Gas", b =>
                {
                    b.HasBaseType("ConsoleApp2.Models.Layer");

                    b.Property<int>("GasTypeId")
                        .HasColumnType("int");

                    b.HasIndex("GasTypeId");

                    b.ToTable("Gas", (string)null);
                });

            modelBuilder.Entity("ConsoleApp2.Models.PVB", b =>
                {
                    b.HasBaseType("ConsoleApp2.Models.Layer");

                    b.Property<int>("PVBTypeId")
                        .HasColumnType("int");

                    b.HasIndex("PVBTypeId");

                    b.ToTable("PVB", (string)null);
                });

            modelBuilder.Entity("ConsoleApp2.Models.Substrate", b =>
                {
                    b.HasBaseType("ConsoleApp2.Models.Layer");

                    b.Property<int?>("InnerCoatingId")
                        .HasColumnType("int");

                    b.Property<int?>("OuterCoatingId")
                        .HasColumnType("int");

                    b.Property<int>("SubstrateTypeId")
                        .HasColumnType("int");

                    b.HasIndex("InnerCoatingId");

                    b.HasIndex("OuterCoatingId");

                    b.HasIndex("SubstrateTypeId");

                    b.ToTable("Substrate", (string)null);
                });

            modelBuilder.Entity("ConsoleApp2.Models.Coating", b =>
                {
                    b.HasOne("ConsoleApp2.Models.CoatingSurface", "CoatingSurface")
                        .WithMany()
                        .HasForeignKey("CoatingSurfaceId");

                    b.HasOne("ConsoleApp2.Models.CoatingType", "CoatingType")
                        .WithMany()
                        .HasForeignKey("CoatingTypeId");

                    b.Navigation("CoatingSurface");

                    b.Navigation("CoatingType");
                });

            modelBuilder.Entity("ConsoleApp2.Models.Layer", b =>
                {
                    b.HasOne("ConsoleApp2.Models.LayerType", "LayerType")
                        .WithMany()
                        .HasForeignKey("LayerTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsoleApp2.Models.Makeup", null)
                        .WithMany("Layers")
                        .HasForeignKey("MakeupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LayerType");
                });

            modelBuilder.Entity("ConsoleApp2.Models.Makeup", b =>
                {
                    b.HasOne("ConsoleApp2.Models.CalculationState", "CalculationState")
                        .WithMany()
                        .HasForeignKey("CalculationStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsoleApp2.Models.MakeupType", "MakeupType")
                        .WithMany()
                        .HasForeignKey("MakeupTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsoleApp2.Models.Project", "Project")
                        .WithMany("Makeups")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalculationState");

                    b.Navigation("MakeupType");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ConsoleApp2.Models.MakeupWarning", b =>
                {
                    b.HasOne("ConsoleApp2.Models.Makeup", null)
                        .WithMany("Warnings")
                        .HasForeignKey("MakeupId");

                    b.HasOne("ConsoleApp2.Models.WarningType", "WarningType")
                        .WithMany()
                        .HasForeignKey("WarningTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WarningType");
                });

            modelBuilder.Entity("ConsoleApp2.Models.ParameterValue", b =>
                {
                    b.HasOne("ConsoleApp2.Models.Makeup", "Makeup")
                        .WithMany("ParameterValues")
                        .HasForeignKey("MakeupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsoleApp2.Models.Parameter", "Parameter")
                        .WithMany("ParameterValues")
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Makeup");

                    b.Navigation("Parameter");
                });

            modelBuilder.Entity("ConsoleApp2.Models.Project", b =>
                {
                    b.HasOne("ConsoleApp2.Models.AirMass", "AirMass")
                        .WithMany()
                        .HasForeignKey("AirMassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsoleApp2.Models.Illuminant", "Illuminant")
                        .WithMany()
                        .HasForeignKey("IlluminantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsoleApp2.Models.Observer", "Observer")
                        .WithMany()
                        .HasForeignKey("ObserverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsoleApp2.Models.Standart", "Standart")
                        .WithMany()
                        .HasForeignKey("StandartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AirMass");

                    b.Navigation("Illuminant");

                    b.Navigation("Observer");

                    b.Navigation("Standart");
                });

            modelBuilder.Entity("ConsoleApp2.Models.Gas", b =>
                {
                    b.HasOne("ConsoleApp2.Models.GasType", "GasType")
                        .WithMany()
                        .HasForeignKey("GasTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsoleApp2.Models.Layer", null)
                        .WithOne()
                        .HasForeignKey("ConsoleApp2.Models.Gas", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GasType");
                });

            modelBuilder.Entity("ConsoleApp2.Models.PVB", b =>
                {
                    b.HasOne("ConsoleApp2.Models.Layer", null)
                        .WithOne()
                        .HasForeignKey("ConsoleApp2.Models.PVB", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsoleApp2.Models.PVBType", "PVBType")
                        .WithMany()
                        .HasForeignKey("PVBTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PVBType");
                });

            modelBuilder.Entity("ConsoleApp2.Models.Substrate", b =>
                {
                    b.HasOne("ConsoleApp2.Models.Layer", null)
                        .WithOne()
                        .HasForeignKey("ConsoleApp2.Models.Substrate", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsoleApp2.Models.Coating", "InnerCoating")
                        .WithMany()
                        .HasForeignKey("InnerCoatingId");

                    b.HasOne("ConsoleApp2.Models.Coating", "OuterCoating")
                        .WithMany()
                        .HasForeignKey("OuterCoatingId");

                    b.HasOne("ConsoleApp2.Models.SubstrateType", "SubstrateType")
                        .WithMany()
                        .HasForeignKey("SubstrateTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InnerCoating");

                    b.Navigation("OuterCoating");

                    b.Navigation("SubstrateType");
                });

            modelBuilder.Entity("ConsoleApp2.Models.Makeup", b =>
                {
                    b.Navigation("Layers");

                    b.Navigation("ParameterValues");

                    b.Navigation("Warnings");
                });

            modelBuilder.Entity("ConsoleApp2.Models.Parameter", b =>
                {
                    b.Navigation("ParameterValues");
                });

            modelBuilder.Entity("ConsoleApp2.Models.Project", b =>
                {
                    b.Navigation("Makeups");
                });
#pragma warning restore 612, 618
        }
    }
}
